### ISSUE TITLE
problem with fetch

### ISSUE THREAD

**Issue by kierangillen** [zonkphins/project3#16]
Hey there,
We're having a problem with fetch. It may be that the fetch is taking too long but its returning nothing. The link is good though so it should work.

@gittheking
@jasonseminara
@trevorpreston
@rapala61
@irwintsay

**Comment by gittheking** [comment]
@kierangillen Please adhere to our assistance guideline. We need a code snippet, description of what you tried doing to solve it, error codes if there are any.
