### ISSUE TITLE
I'm having a small problem with the css

### ISSUE THREAD

**Issue by kierangillen** [zonkphins/project3#27]
Hey I'm having an issue with our css- a square div is being pushed down from where I'd expect it to be by about 90px.

```
.bing-container {
  height: 545px;
  width: 545px;
  border: 2px solid black;
  display: inline-block;
  position: relative;
}
```

This is the container that is moving. I'm not quite sure which other code to share because I'm not sure what specifically is manipulating it. I've tried unclicking all the css in the developer tools and I can't find what it is.

-Kieran

Bobby - @gittheking
Jason - @jasonseminara
Trevor - @trevorpreston
Rafa - @rapala61
Irwin - @irwintsay

**Comment by trevorpreston** [comment]
Still want to chat about this?

**Comment by kierangillen** [comment]
yes indeed i would

**Comment by trevorpreston** [comment]
come to long tables on 2

**Comment by gittheking** [comment]
@kierangillen please close this when you get a chance.
